apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - rollout-api.yaml
  - rollout-frontend.yaml
  - analysis-template-api.yaml

images:
  - name: ghcr.io/davidnguyen/yts-api
    newName: ghcr.io/davidnguyen/yts-api
    newTag: canary
  - name: ghcr.io/davidnguyen/yts-frontend
    newName: ghcr.io/davidnguyen/yts-frontend
    newTag: canary

patches:
  - path: delete-deployment-api.yaml
  - path: delete-deployment-frontend.yaml
  - path: patch-hpa-api.yaml
  - path: patch-hpa-frontend.yaml
  - path: patch-configmap.yaml
