apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/davidnguyen/yts-api
    newName: ghcr.io/davidnguyen/yts-api
    newTag: stable
  - name: ghcr.io/davidnguyen/yts-frontend
    newName: ghcr.io/davidnguyen/yts-frontend
    newTag: stable

patches:
  - path: patch-configmap.yaml
  - path: patch-ingress-host.yaml
