global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts/yts-api-alerts.yml

scrape_configs:
  - job_name: yts-api-local
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: yts-api-k8s
    metrics_path: /metrics
    static_configs:
      - targets: ["yts-api.yts-prod.svc.cluster.local:8000"]
