apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yts-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
spec:
  tls:
    - hosts:
        - api.youtube-success.example.com
        - youtube-success.example.com
      secretName: yts-tls
  rules:
    - host: api.youtube-success.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: yts-api
                port:
                  number: 8000
    - host: youtube-success.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: yts-frontend
                port:
                  number: 3000
