apiVersion: v1
kind: Secret
metadata:
  name: yts-secrets
  labels:
    app.kubernetes.io/name: youtube-success-ml
type: Opaque
stringData:
  CORS_ALLOWED_ORIGINS: "https://youtube-success.example.com"
  SENTRY_DSN: "replace-me"
