apiVersion: v1
kind: Service
metadata:
  name: yts-frontend
  labels:
    app.kubernetes.io/name: yts-frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: yts-frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
